name: ServerChannels
main: ServerChannels\Main
version: "1.2"
api: [1.11.0]
load: STARTUP
author: EvolSoft
description: Create customized chat channels
website: http://www.evolsoft.tk

commands:
 serverchannels:
   aliases: [serverch, sch, ch]
   description: ServerChannels commands.
   permission: serverchannels
   
permissions:
 serverchannels:
  default: true
  description: ServerChannels permissions.
  children:
   serverchannels.channels:
    default: true
    description: ServerChannels channels permissions.
   serverchannels.commands:
    default: true
    description: ServerChannels commands permissions.
    children:
      serverchannels.commands.help:
       default: true
       description: ServerChannels command Help permission.
      serverchannels.commands.info:
       default: true
       description: ServerChannels command Info permission.
      serverchannels.commands.reload:
       default: true
       description: ServerChannels command Reload permission.
      serverchannels.commands.list:
       default: true
       description: ServerChannels command List permission.
      serverchannels.commands.join:
       default: true
       description: ServerChannels command Join permission.
      serverchannels.commands.leave:
       default: true
       description: ServerChannels command Leave permission.
      serverchannels.commands.new:
       default: true
       description: ServerChannels command New permission.
